---
# Install and run filebeat

- name: "Installing filebeat on current OS"
  include_tasks: '{{ platform_tasks }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - system/not-supported.yml
  loop_control:
    loop_var: platform_tasks
