---

- name: Install dependency for Debian
  become: True
  package:
    name: apt-transport-https
    state: present

- name: Add elasticsearch apt key
  become: True
  apt_key:
    url: '{{ elastic_gpg_key }}'
    state: present

- name: Add Beats repository for {{ ansible_os_family }}
  become: True
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elastic_branch }}.x/apt stable main'
    state: present
    update_cache: true

- name: Install filebeat
  become: True
  package:
    name: filebeat
    state: present
  register: installed_package
  until: installed_package is succeeded

- name: Copy Configuration File
  become: True
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0644
  notify: Restart filebeat
  