---
- name: Install dependency for Debian
  become: True
  package:
    name: apt-transport-https
    state: present
  register: debian_dependency
  until: debian_dependency is succeeded

- name: Add elasticsearch apt key
  become: True
  apt_key:
    url: '{{ elastic_gpg_key }}'
    state: present
  register: add_gpg_key
  until: add_gpg_key is succeeded

- name: Add Beats repository
  become: True
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ filebeat_version }}/apt stable main'
    state: present
    update_cache: True

- name: Install filebeat
  become: True
  package:
    name: filebeat
    state: present
  register: installed_package
  until: installed_package is succeeded

- name: Setup path folders
  become: True
  file:
    path: '{{ path_folder.value }}'
    state: directory
  with_dict: '{{ path }}'
  loop_control:
    loop_var: path_folder

- name: Copy Configuration File
  become: True
  template:
    src: filebeat.yml.j2
    dest: '{{ path.config }}/filebeat.yml'
    owner: root
    group: root
    mode: 0644

- name: Create folder path for service script
  become: True
  file:
    path: /usr/lib/systemd/system
    state: directory

- name: templating init script
  become: True
  template:
    src: '{{ filebeat.service.template }}.j2'
    dest: '{{ filebeat.service.path }}'
    owner: root
    group: root
    mode: u+rwx
  notify: '{{ filebeat.service.handler }}'
