---
# handlers file for ansible-role-filebeat
- name: start_filebeat_systemd
  become: true
  systemd:
    name: filebeat
    state: started
    enabled: true
    daemon-reload: true

- name: start_filebeat_initd
  become: true
  service:
    name: filebeat
    pattern: "{{ path.home }}/bin/filebeat"
    state: started
    enabled: true
