---
# handlers file for ansible-role-filebeat
- name: Reload systemd configuration
  systemd:
    daemon_reload: true
  become: true

- name: Restart filebeat
  service:
    name: '{{ filebeat_service_name }}'
    state: restarted
  become: true

- name: Restart filebeat win
  win_service:
    name: '{{ filebeat_service_name }}'
    state: restarted
